/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as AuthenticatedRecruiterRouteImport } from './routes/_authenticated/recruiter'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated/feed'
import { Route as AuthenticatedRecruiterTemplatesRouteImport } from './routes/_authenticated/recruiter_.templates'
import { Route as AuthenticatedRecruiterQuestionBankRouteImport } from './routes/_authenticated/recruiter_.question-bank'
import { Route as AuthenticatedRecruiterMessageTemplatesRouteImport } from './routes/_authenticated/recruiter_.message-templates'
import { Route as AuthenticatedRecruiterCompanyRouteImport } from './routes/_authenticated/recruiter_.company'
import { Route as AuthenticatedRecruiterAuditRouteImport } from './routes/_authenticated/recruiter_.audit'
import { Route as AuthenticatedMeSavedRouteImport } from './routes/_authenticated/me.saved'
import { Route as AuthenticatedMeNotificationsRouteImport } from './routes/_authenticated/me.notifications'
import { Route as AuthenticatedMeApplicationsRouteImport } from './routes/_authenticated/me.applications'
import { Route as AuthenticatedInterviewInterviewIdRouteImport } from './routes/_authenticated/interview.$interviewId'
import { Route as AuthenticatedApplyJobIdRouteImport } from './routes/_authenticated/apply.$jobId'
import { Route as AuthenticatedAdminVerificationsRouteImport } from './routes/_authenticated/admin.verifications'
import { Route as AuthenticatedRecruiterJobsNewRouteImport } from './routes/_authenticated/recruiter_.jobs.new'
import { Route as AuthenticatedRecruiterJobsJobIdRouteImport } from './routes/_authenticated/recruiter_.jobs.$jobId'
import { Route as AuthenticatedRecruiterApplicationsApplicationIdRouteImport } from './routes/_authenticated/recruiter_.applications.$applicationId'
import { Route as AuthenticatedMeApplicationsApplicationIdRouteImport } from './routes/_authenticated/me.applications.$applicationId'
import { Route as AuthenticatedApplyJobIdInterviewRouteImport } from './routes/_authenticated/apply.$jobId.interview'
import { Route as ApiPublicOgJobsFileRouteImport } from './routes/api/public/og.jobs.$file'
import { Route as AuthenticatedRecruiterJobsJobIdPipelineRouteImport } from './routes/_authenticated/recruiter_.jobs.$jobId.pipeline'
import { Route as AuthenticatedRecruiterJobsJobIdCompareRouteImport } from './routes/_authenticated/recruiter_.jobs.$jobId.compare'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRecruiterRoute = AuthenticatedRecruiterRouteImport.update({
  id: '/recruiter',
  path: '/recruiter',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecruiterTemplatesRoute =
  AuthenticatedRecruiterTemplatesRouteImport.update({
    id: '/recruiter_/templates',
    path: '/recruiter/templates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecruiterQuestionBankRoute =
  AuthenticatedRecruiterQuestionBankRouteImport.update({
    id: '/recruiter_/question-bank',
    path: '/recruiter/question-bank',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecruiterMessageTemplatesRoute =
  AuthenticatedRecruiterMessageTemplatesRouteImport.update({
    id: '/recruiter_/message-templates',
    path: '/recruiter/message-templates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecruiterCompanyRoute =
  AuthenticatedRecruiterCompanyRouteImport.update({
    id: '/recruiter_/company',
    path: '/recruiter/company',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecruiterAuditRoute =
  AuthenticatedRecruiterAuditRouteImport.update({
    id: '/recruiter_/audit',
    path: '/recruiter/audit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMeSavedRoute = AuthenticatedMeSavedRouteImport.update({
  id: '/me/saved',
  path: '/me/saved',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeNotificationsRoute =
  AuthenticatedMeNotificationsRouteImport.update({
    id: '/me/notifications',
    path: '/me/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMeApplicationsRoute =
  AuthenticatedMeApplicationsRouteImport.update({
    id: '/me/applications',
    path: '/me/applications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInterviewInterviewIdRoute =
  AuthenticatedInterviewInterviewIdRouteImport.update({
    id: '/interview/$interviewId',
    path: '/interview/$interviewId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedApplyJobIdRoute = AuthenticatedApplyJobIdRouteImport.update({
  id: '/apply/$jobId',
  path: '/apply/$jobId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminVerificationsRoute =
  AuthenticatedAdminVerificationsRouteImport.update({
    id: '/admin/verifications',
    path: '/admin/verifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecruiterJobsNewRoute =
  AuthenticatedRecruiterJobsNewRouteImport.update({
    id: '/recruiter_/jobs/new',
    path: '/recruiter/jobs/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecruiterJobsJobIdRoute =
  AuthenticatedRecruiterJobsJobIdRouteImport.update({
    id: '/recruiter_/jobs/$jobId',
    path: '/recruiter/jobs/$jobId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecruiterApplicationsApplicationIdRoute =
  AuthenticatedRecruiterApplicationsApplicationIdRouteImport.update({
    id: '/recruiter_/applications/$applicationId',
    path: '/recruiter/applications/$applicationId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMeApplicationsApplicationIdRoute =
  AuthenticatedMeApplicationsApplicationIdRouteImport.update({
    id: '/$applicationId',
    path: '/$applicationId',
    getParentRoute: () => AuthenticatedMeApplicationsRoute,
  } as any)
const AuthenticatedApplyJobIdInterviewRoute =
  AuthenticatedApplyJobIdInterviewRouteImport.update({
    id: '/interview',
    path: '/interview',
    getParentRoute: () => AuthenticatedApplyJobIdRoute,
  } as any)
const ApiPublicOgJobsFileRoute = ApiPublicOgJobsFileRouteImport.update({
  id: '/api/public/og/jobs/$file',
  path: '/api/public/og/jobs/$file',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRecruiterJobsJobIdPipelineRoute =
  AuthenticatedRecruiterJobsJobIdPipelineRouteImport.update({
    id: '/pipeline',
    path: '/pipeline',
    getParentRoute: () => AuthenticatedRecruiterJobsJobIdRoute,
  } as any)
const AuthenticatedRecruiterJobsJobIdCompareRoute =
  AuthenticatedRecruiterJobsJobIdCompareRouteImport.update({
    id: '/compare',
    path: '/compare',
    getParentRoute: () => AuthenticatedRecruiterJobsJobIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/recruiter': typeof AuthenticatedRecruiterRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/admin/verifications': typeof AuthenticatedAdminVerificationsRoute
  '/apply/$jobId': typeof AuthenticatedApplyJobIdRouteWithChildren
  '/interview/$interviewId': typeof AuthenticatedInterviewInterviewIdRoute
  '/me/applications': typeof AuthenticatedMeApplicationsRouteWithChildren
  '/me/notifications': typeof AuthenticatedMeNotificationsRoute
  '/me/saved': typeof AuthenticatedMeSavedRoute
  '/recruiter/audit': typeof AuthenticatedRecruiterAuditRoute
  '/recruiter/company': typeof AuthenticatedRecruiterCompanyRoute
  '/recruiter/message-templates': typeof AuthenticatedRecruiterMessageTemplatesRoute
  '/recruiter/question-bank': typeof AuthenticatedRecruiterQuestionBankRoute
  '/recruiter/templates': typeof AuthenticatedRecruiterTemplatesRoute
  '/apply/$jobId/interview': typeof AuthenticatedApplyJobIdInterviewRoute
  '/me/applications/$applicationId': typeof AuthenticatedMeApplicationsApplicationIdRoute
  '/recruiter/applications/$applicationId': typeof AuthenticatedRecruiterApplicationsApplicationIdRoute
  '/recruiter/jobs/$jobId': typeof AuthenticatedRecruiterJobsJobIdRouteWithChildren
  '/recruiter/jobs/new': typeof AuthenticatedRecruiterJobsNewRoute
  '/recruiter/jobs/$jobId/compare': typeof AuthenticatedRecruiterJobsJobIdCompareRoute
  '/recruiter/jobs/$jobId/pipeline': typeof AuthenticatedRecruiterJobsJobIdPipelineRoute
  '/api/public/og/jobs/$file': typeof ApiPublicOgJobsFileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/recruiter': typeof AuthenticatedRecruiterRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/admin/verifications': typeof AuthenticatedAdminVerificationsRoute
  '/apply/$jobId': typeof AuthenticatedApplyJobIdRouteWithChildren
  '/interview/$interviewId': typeof AuthenticatedInterviewInterviewIdRoute
  '/me/applications': typeof AuthenticatedMeApplicationsRouteWithChildren
  '/me/notifications': typeof AuthenticatedMeNotificationsRoute
  '/me/saved': typeof AuthenticatedMeSavedRoute
  '/recruiter/audit': typeof AuthenticatedRecruiterAuditRoute
  '/recruiter/company': typeof AuthenticatedRecruiterCompanyRoute
  '/recruiter/message-templates': typeof AuthenticatedRecruiterMessageTemplatesRoute
  '/recruiter/question-bank': typeof AuthenticatedRecruiterQuestionBankRoute
  '/recruiter/templates': typeof AuthenticatedRecruiterTemplatesRoute
  '/apply/$jobId/interview': typeof AuthenticatedApplyJobIdInterviewRoute
  '/me/applications/$applicationId': typeof AuthenticatedMeApplicationsApplicationIdRoute
  '/recruiter/applications/$applicationId': typeof AuthenticatedRecruiterApplicationsApplicationIdRoute
  '/recruiter/jobs/$jobId': typeof AuthenticatedRecruiterJobsJobIdRouteWithChildren
  '/recruiter/jobs/new': typeof AuthenticatedRecruiterJobsNewRoute
  '/recruiter/jobs/$jobId/compare': typeof AuthenticatedRecruiterJobsJobIdCompareRoute
  '/recruiter/jobs/$jobId/pipeline': typeof AuthenticatedRecruiterJobsJobIdPipelineRoute
  '/api/public/og/jobs/$file': typeof ApiPublicOgJobsFileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/recruiter': typeof AuthenticatedRecruiterRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/_authenticated/admin/verifications': typeof AuthenticatedAdminVerificationsRoute
  '/_authenticated/apply/$jobId': typeof AuthenticatedApplyJobIdRouteWithChildren
  '/_authenticated/interview/$interviewId': typeof AuthenticatedInterviewInterviewIdRoute
  '/_authenticated/me/applications': typeof AuthenticatedMeApplicationsRouteWithChildren
  '/_authenticated/me/notifications': typeof AuthenticatedMeNotificationsRoute
  '/_authenticated/me/saved': typeof AuthenticatedMeSavedRoute
  '/_authenticated/recruiter_/audit': typeof AuthenticatedRecruiterAuditRoute
  '/_authenticated/recruiter_/company': typeof AuthenticatedRecruiterCompanyRoute
  '/_authenticated/recruiter_/message-templates': typeof AuthenticatedRecruiterMessageTemplatesRoute
  '/_authenticated/recruiter_/question-bank': typeof AuthenticatedRecruiterQuestionBankRoute
  '/_authenticated/recruiter_/templates': typeof AuthenticatedRecruiterTemplatesRoute
  '/_authenticated/apply/$jobId/interview': typeof AuthenticatedApplyJobIdInterviewRoute
  '/_authenticated/me/applications/$applicationId': typeof AuthenticatedMeApplicationsApplicationIdRoute
  '/_authenticated/recruiter_/applications/$applicationId': typeof AuthenticatedRecruiterApplicationsApplicationIdRoute
  '/_authenticated/recruiter_/jobs/$jobId': typeof AuthenticatedRecruiterJobsJobIdRouteWithChildren
  '/_authenticated/recruiter_/jobs/new': typeof AuthenticatedRecruiterJobsNewRoute
  '/_authenticated/recruiter_/jobs/$jobId/compare': typeof AuthenticatedRecruiterJobsJobIdCompareRoute
  '/_authenticated/recruiter_/jobs/$jobId/pipeline': typeof AuthenticatedRecruiterJobsJobIdPipelineRoute
  '/api/public/og/jobs/$file': typeof ApiPublicOgJobsFileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/feed'
    | '/recruiter'
    | '/jobs/$jobId'
    | '/admin/verifications'
    | '/apply/$jobId'
    | '/interview/$interviewId'
    | '/me/applications'
    | '/me/notifications'
    | '/me/saved'
    | '/recruiter/audit'
    | '/recruiter/company'
    | '/recruiter/message-templates'
    | '/recruiter/question-bank'
    | '/recruiter/templates'
    | '/apply/$jobId/interview'
    | '/me/applications/$applicationId'
    | '/recruiter/applications/$applicationId'
    | '/recruiter/jobs/$jobId'
    | '/recruiter/jobs/new'
    | '/recruiter/jobs/$jobId/compare'
    | '/recruiter/jobs/$jobId/pipeline'
    | '/api/public/og/jobs/$file'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/feed'
    | '/recruiter'
    | '/jobs/$jobId'
    | '/admin/verifications'
    | '/apply/$jobId'
    | '/interview/$interviewId'
    | '/me/applications'
    | '/me/notifications'
    | '/me/saved'
    | '/recruiter/audit'
    | '/recruiter/company'
    | '/recruiter/message-templates'
    | '/recruiter/question-bank'
    | '/recruiter/templates'
    | '/apply/$jobId/interview'
    | '/me/applications/$applicationId'
    | '/recruiter/applications/$applicationId'
    | '/recruiter/jobs/$jobId'
    | '/recruiter/jobs/new'
    | '/recruiter/jobs/$jobId/compare'
    | '/recruiter/jobs/$jobId/pipeline'
    | '/api/public/og/jobs/$file'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/feed'
    | '/_authenticated/recruiter'
    | '/jobs/$jobId'
    | '/_authenticated/admin/verifications'
    | '/_authenticated/apply/$jobId'
    | '/_authenticated/interview/$interviewId'
    | '/_authenticated/me/applications'
    | '/_authenticated/me/notifications'
    | '/_authenticated/me/saved'
    | '/_authenticated/recruiter_/audit'
    | '/_authenticated/recruiter_/company'
    | '/_authenticated/recruiter_/message-templates'
    | '/_authenticated/recruiter_/question-bank'
    | '/_authenticated/recruiter_/templates'
    | '/_authenticated/apply/$jobId/interview'
    | '/_authenticated/me/applications/$applicationId'
    | '/_authenticated/recruiter_/applications/$applicationId'
    | '/_authenticated/recruiter_/jobs/$jobId'
    | '/_authenticated/recruiter_/jobs/new'
    | '/_authenticated/recruiter_/jobs/$jobId/compare'
    | '/_authenticated/recruiter_/jobs/$jobId/pipeline'
    | '/api/public/og/jobs/$file'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
  ApiPublicOgJobsFileRoute: typeof ApiPublicOgJobsFileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/recruiter': {
      id: '/_authenticated/recruiter'
      path: '/recruiter'
      fullPath: '/recruiter'
      preLoaderRoute: typeof AuthenticatedRecruiterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recruiter_/templates': {
      id: '/_authenticated/recruiter_/templates'
      path: '/recruiter/templates'
      fullPath: '/recruiter/templates'
      preLoaderRoute: typeof AuthenticatedRecruiterTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recruiter_/question-bank': {
      id: '/_authenticated/recruiter_/question-bank'
      path: '/recruiter/question-bank'
      fullPath: '/recruiter/question-bank'
      preLoaderRoute: typeof AuthenticatedRecruiterQuestionBankRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recruiter_/message-templates': {
      id: '/_authenticated/recruiter_/message-templates'
      path: '/recruiter/message-templates'
      fullPath: '/recruiter/message-templates'
      preLoaderRoute: typeof AuthenticatedRecruiterMessageTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recruiter_/company': {
      id: '/_authenticated/recruiter_/company'
      path: '/recruiter/company'
      fullPath: '/recruiter/company'
      preLoaderRoute: typeof AuthenticatedRecruiterCompanyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recruiter_/audit': {
      id: '/_authenticated/recruiter_/audit'
      path: '/recruiter/audit'
      fullPath: '/recruiter/audit'
      preLoaderRoute: typeof AuthenticatedRecruiterAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/me/saved': {
      id: '/_authenticated/me/saved'
      path: '/me/saved'
      fullPath: '/me/saved'
      preLoaderRoute: typeof AuthenticatedMeSavedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/me/notifications': {
      id: '/_authenticated/me/notifications'
      path: '/me/notifications'
      fullPath: '/me/notifications'
      preLoaderRoute: typeof AuthenticatedMeNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/me/applications': {
      id: '/_authenticated/me/applications'
      path: '/me/applications'
      fullPath: '/me/applications'
      preLoaderRoute: typeof AuthenticatedMeApplicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interview/$interviewId': {
      id: '/_authenticated/interview/$interviewId'
      path: '/interview/$interviewId'
      fullPath: '/interview/$interviewId'
      preLoaderRoute: typeof AuthenticatedInterviewInterviewIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apply/$jobId': {
      id: '/_authenticated/apply/$jobId'
      path: '/apply/$jobId'
      fullPath: '/apply/$jobId'
      preLoaderRoute: typeof AuthenticatedApplyJobIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/verifications': {
      id: '/_authenticated/admin/verifications'
      path: '/admin/verifications'
      fullPath: '/admin/verifications'
      preLoaderRoute: typeof AuthenticatedAdminVerificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recruiter_/jobs/new': {
      id: '/_authenticated/recruiter_/jobs/new'
      path: '/recruiter/jobs/new'
      fullPath: '/recruiter/jobs/new'
      preLoaderRoute: typeof AuthenticatedRecruiterJobsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recruiter_/jobs/$jobId': {
      id: '/_authenticated/recruiter_/jobs/$jobId'
      path: '/recruiter/jobs/$jobId'
      fullPath: '/recruiter/jobs/$jobId'
      preLoaderRoute: typeof AuthenticatedRecruiterJobsJobIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recruiter_/applications/$applicationId': {
      id: '/_authenticated/recruiter_/applications/$applicationId'
      path: '/recruiter/applications/$applicationId'
      fullPath: '/recruiter/applications/$applicationId'
      preLoaderRoute: typeof AuthenticatedRecruiterApplicationsApplicationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/me/applications/$applicationId': {
      id: '/_authenticated/me/applications/$applicationId'
      path: '/$applicationId'
      fullPath: '/me/applications/$applicationId'
      preLoaderRoute: typeof AuthenticatedMeApplicationsApplicationIdRouteImport
      parentRoute: typeof AuthenticatedMeApplicationsRoute
    }
    '/_authenticated/apply/$jobId/interview': {
      id: '/_authenticated/apply/$jobId/interview'
      path: '/interview'
      fullPath: '/apply/$jobId/interview'
      preLoaderRoute: typeof AuthenticatedApplyJobIdInterviewRouteImport
      parentRoute: typeof AuthenticatedApplyJobIdRoute
    }
    '/api/public/og/jobs/$file': {
      id: '/api/public/og/jobs/$file'
      path: '/api/public/og/jobs/$file'
      fullPath: '/api/public/og/jobs/$file'
      preLoaderRoute: typeof ApiPublicOgJobsFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/recruiter_/jobs/$jobId/pipeline': {
      id: '/_authenticated/recruiter_/jobs/$jobId/pipeline'
      path: '/pipeline'
      fullPath: '/recruiter/jobs/$jobId/pipeline'
      preLoaderRoute: typeof AuthenticatedRecruiterJobsJobIdPipelineRouteImport
      parentRoute: typeof AuthenticatedRecruiterJobsJobIdRoute
    }
    '/_authenticated/recruiter_/jobs/$jobId/compare': {
      id: '/_authenticated/recruiter_/jobs/$jobId/compare'
      path: '/compare'
      fullPath: '/recruiter/jobs/$jobId/compare'
      preLoaderRoute: typeof AuthenticatedRecruiterJobsJobIdCompareRouteImport
      parentRoute: typeof AuthenticatedRecruiterJobsJobIdRoute
    }
  }
}

interface AuthenticatedApplyJobIdRouteChildren {
  AuthenticatedApplyJobIdInterviewRoute: typeof AuthenticatedApplyJobIdInterviewRoute
}

const AuthenticatedApplyJobIdRouteChildren: AuthenticatedApplyJobIdRouteChildren =
  {
    AuthenticatedApplyJobIdInterviewRoute:
      AuthenticatedApplyJobIdInterviewRoute,
  }

const AuthenticatedApplyJobIdRouteWithChildren =
  AuthenticatedApplyJobIdRoute._addFileChildren(
    AuthenticatedApplyJobIdRouteChildren,
  )

interface AuthenticatedMeApplicationsRouteChildren {
  AuthenticatedMeApplicationsApplicationIdRoute: typeof AuthenticatedMeApplicationsApplicationIdRoute
}

const AuthenticatedMeApplicationsRouteChildren: AuthenticatedMeApplicationsRouteChildren =
  {
    AuthenticatedMeApplicationsApplicationIdRoute:
      AuthenticatedMeApplicationsApplicationIdRoute,
  }

const AuthenticatedMeApplicationsRouteWithChildren =
  AuthenticatedMeApplicationsRoute._addFileChildren(
    AuthenticatedMeApplicationsRouteChildren,
  )

interface AuthenticatedRecruiterJobsJobIdRouteChildren {
  AuthenticatedRecruiterJobsJobIdCompareRoute: typeof AuthenticatedRecruiterJobsJobIdCompareRoute
  AuthenticatedRecruiterJobsJobIdPipelineRoute: typeof AuthenticatedRecruiterJobsJobIdPipelineRoute
}

const AuthenticatedRecruiterJobsJobIdRouteChildren: AuthenticatedRecruiterJobsJobIdRouteChildren =
  {
    AuthenticatedRecruiterJobsJobIdCompareRoute:
      AuthenticatedRecruiterJobsJobIdCompareRoute,
    AuthenticatedRecruiterJobsJobIdPipelineRoute:
      AuthenticatedRecruiterJobsJobIdPipelineRoute,
  }

const AuthenticatedRecruiterJobsJobIdRouteWithChildren =
  AuthenticatedRecruiterJobsJobIdRoute._addFileChildren(
    AuthenticatedRecruiterJobsJobIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedRecruiterRoute: typeof AuthenticatedRecruiterRoute
  AuthenticatedAdminVerificationsRoute: typeof AuthenticatedAdminVerificationsRoute
  AuthenticatedApplyJobIdRoute: typeof AuthenticatedApplyJobIdRouteWithChildren
  AuthenticatedInterviewInterviewIdRoute: typeof AuthenticatedInterviewInterviewIdRoute
  AuthenticatedMeApplicationsRoute: typeof AuthenticatedMeApplicationsRouteWithChildren
  AuthenticatedMeNotificationsRoute: typeof AuthenticatedMeNotificationsRoute
  AuthenticatedMeSavedRoute: typeof AuthenticatedMeSavedRoute
  AuthenticatedRecruiterAuditRoute: typeof AuthenticatedRecruiterAuditRoute
  AuthenticatedRecruiterCompanyRoute: typeof AuthenticatedRecruiterCompanyRoute
  AuthenticatedRecruiterMessageTemplatesRoute: typeof AuthenticatedRecruiterMessageTemplatesRoute
  AuthenticatedRecruiterQuestionBankRoute: typeof AuthenticatedRecruiterQuestionBankRoute
  AuthenticatedRecruiterTemplatesRoute: typeof AuthenticatedRecruiterTemplatesRoute
  AuthenticatedRecruiterApplicationsApplicationIdRoute: typeof AuthenticatedRecruiterApplicationsApplicationIdRoute
  AuthenticatedRecruiterJobsJobIdRoute: typeof AuthenticatedRecruiterJobsJobIdRouteWithChildren
  AuthenticatedRecruiterJobsNewRoute: typeof AuthenticatedRecruiterJobsNewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedRecruiterRoute: AuthenticatedRecruiterRoute,
  AuthenticatedAdminVerificationsRoute: AuthenticatedAdminVerificationsRoute,
  AuthenticatedApplyJobIdRoute: AuthenticatedApplyJobIdRouteWithChildren,
  AuthenticatedInterviewInterviewIdRoute:
    AuthenticatedInterviewInterviewIdRoute,
  AuthenticatedMeApplicationsRoute:
    AuthenticatedMeApplicationsRouteWithChildren,
  AuthenticatedMeNotificationsRoute: AuthenticatedMeNotificationsRoute,
  AuthenticatedMeSavedRoute: AuthenticatedMeSavedRoute,
  AuthenticatedRecruiterAuditRoute: AuthenticatedRecruiterAuditRoute,
  AuthenticatedRecruiterCompanyRoute: AuthenticatedRecruiterCompanyRoute,
  AuthenticatedRecruiterMessageTemplatesRoute:
    AuthenticatedRecruiterMessageTemplatesRoute,
  AuthenticatedRecruiterQuestionBankRoute:
    AuthenticatedRecruiterQuestionBankRoute,
  AuthenticatedRecruiterTemplatesRoute: AuthenticatedRecruiterTemplatesRoute,
  AuthenticatedRecruiterApplicationsApplicationIdRoute:
    AuthenticatedRecruiterApplicationsApplicationIdRoute,
  AuthenticatedRecruiterJobsJobIdRoute:
    AuthenticatedRecruiterJobsJobIdRouteWithChildren,
  AuthenticatedRecruiterJobsNewRoute: AuthenticatedRecruiterJobsNewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  JobsJobIdRoute: JobsJobIdRoute,
  ApiPublicOgJobsFileRoute: ApiPublicOgJobsFileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
